// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbwXByR3pRreloYThKhZDQTyvQjEQb2CI',
    appId: '1:463285908927:web:d53428c6ee887dd7dfdd0a',
    messagingSenderId: '463285908927',
    projectId: 'lasbite-db994',
    authDomain: 'lasbite-db994.firebaseapp.com',
    storageBucket: 'lasbite-db994.appspot.com',
    measurementId: 'G-SHRSSVLLV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr0Yqt_gXRRvYmj8DgYnIYRG2IHY7lOpc',
    appId: '1:463285908927:android:082cf827614f45abdfdd0a',
    messagingSenderId: '463285908927',
    projectId: 'lasbite-db994',
    storageBucket: 'lasbite-db994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdwy0mie5AwkBPTgQ6H4ioLK_3Ejw-HSQ',
    appId: '1:463285908927:ios:89619150e0f58725dfdd0a',
    messagingSenderId: '463285908927',
    projectId: 'lasbite-db994',
    storageBucket: 'lasbite-db994.appspot.com',
    androidClientId: '463285908927-6ptk22vog4h1975u0rlgv9n4r8u97pij.apps.googleusercontent.com',
    iosClientId: '463285908927-1vaqvaqbk42aticb0v814dhkmm10i5c7.apps.googleusercontent.com',
    iosBundleId: 'com.example.lasbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdwy0mie5AwkBPTgQ6H4ioLK_3Ejw-HSQ',
    appId: '1:463285908927:ios:c9b27412a91f7997dfdd0a',
    messagingSenderId: '463285908927',
    projectId: 'lasbite-db994',
    storageBucket: 'lasbite-db994.appspot.com',
    androidClientId: '463285908927-6ptk22vog4h1975u0rlgv9n4r8u97pij.apps.googleusercontent.com',
    iosClientId: '463285908927-m2u4crsf1468bgfhsu619vh24r365pnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lasbite.RunnerTests',
  );
}
